language: objective-c

xcode_project: PHImageKit.xcodeproj
xcode_scheme: PHImageKit
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
os: osx

before_install:

    - export LANG=en_US.UTF-8
    - gem install cocoapods --quiet

script:

    - pod lib lint --allow-warnings
    - xctool -workspace PHImageKit.xcworkspace -scheme PHImageKitDemo clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO